/* Awakenology Runtime Implementation — Full Automated Migration & Redesign Pipeline v2
 * Runtime/global implementation lives here.
 * Source migration rules: The-Master.md
 * Verification rules: AUDIT.md
 * Inventory/state: migration-manifest.json
 */
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const response = await env.ASSETS.fetch(request);
    const contentType = response.headers.get("content-type") || "";
    const pathname = new URL(request.url).pathname;
    const decodedPathname = decodeURIComponent(pathname);
    const isLanguageTocPage = decodedPathname === "/English/" || decodedPathname === "/Japanese/" || decodedPathname === "/Chinese/";
    const isChinesePage = decodedPathname === "/Chinese/" || decodedPathname === "/Coach_cn/" || (/[^\x00-\x7f]/.test(decodedPathname) && /[\u3400-\u9fff]/.test(decodedPathname) && !/[\u3040-\u30ff]/.test(decodedPathname));
    const legacyDarkPages = [
      "/What-Is-Hypnosis/","/What-Is-Hypnotic-Reincarnation/","/The-History-of-Reincarnation/","/Multidimensional-Body-Complex-1-Single-Complex/","/Multidimensional-Body-Complex-3-Multi-Complex/","/What-is-The-Ultimate-Source/","/What-does-The-Ultimate-Source-like/","/What-is-Multidimensional-Space-Time/","/What-is-Zero-Energy-Space/","/Energy-Consumption-and-Transformation/","/アインシュタイン協議百年催眠実験/","/意識強度とは/","/意識強度検測点1自動意識制御領域/","/意識強度検測点2自主意識領域/","/意識強度検測点抽出検測データサンプル20190317/","/人の多次元複合体構造1-単重複合体/","/人の多次元複合体構造2-二重複合体霊-体/","/伝統修行の五段階/"
    ];
    const isLegacyDarkPage = legacyDarkPages.includes(decodedPathname);
    if (!contentType.toLowerCase().includes("text/html")) return response;

    const theme = `<style id="awakenology-theme-style">
html[data-aw-theme="dark"] body,html[data-aw-theme="dark"] #wb_root,html[data-aw-theme="dark"] .wb_sbg{background-color:#121212!important;color:#e8e8e8!important}
html[data-aw-theme="dark"] body.awakenology-toc-page .wb_content{background-color:#121212!important;color:#e8e8e8!important}
body.awakenology-toc-page #wb_main_a188dda41444018c179704becd58d6e8,body.awakenology-toc-page #wb_main_a188dda414440213c8768efbfc4fa4d8,body.awakenology-toc-page #wb_main_a188dda4144403b540310ab683472666{padding-top:18px!important}
body.awakenology-toc-page h2.wb-stl-heading2{margin:0 0 12px!important;font-family:Georgia,"Times New Roman",serif!important;font-size:34px!important;font-weight:400!important;line-height:1.2!important}
body.awakenology-toc-page .wb-stl-heading2 + p{margin-top:0!important;margin-bottom:26px!important;color:#666!important;letter-spacing:.03em}
body.awakenology-lang-en #a1912b6e909c0001619736f255cd2f4e a[href="/English/"],body.awakenology-lang-en #a1912b6e909c0001619736f255cd2f4e a[href="/English/"] span,body.awakenology-lang-ja #a1912b6e909c0001619736f255cd2f4e a[href="/Japanese/"],body.awakenology-lang-ja #a1912b6e909c0001619736f255cd2f4e a[href="/Japanese/"] span,body.awakenology-lang-zh #a1912b6e909c0001619736f255cd2f4e a[href="/Chinese/"],body.awakenology-lang-zh #a1912b6e909c0001619736f255cd2f4e a[href="/Chinese/"] span{color:#fff!important;opacity:1!important;visibility:visible!important;text-decoration:underline!important;text-decoration-color:#fff!important;text-decoration-thickness:2px!important;text-underline-offset:5px!important}
body.awakenology-toc-page #a1912b6e909c0001619736f255cd2f4e a{margin:0 6px!important;transition:text-decoration-color .15s ease!important}
body.awakenology-toc-page #a1912b6e909c0001619736f255cd2f4e a:hover{color:#fff!important;text-decoration:underline!important;text-decoration-color:#fff!important;text-underline-offset:5px!important}
html[data-aw-theme="dark"] body.awakenology-toc-page .wb-stl-heading2 + p{color:#aaa!important}
@media (max-width:700px){body.awakenology-toc-page #wb_main_a188dda41444018c179704becd58d6e8,body.awakenology-toc-page #wb_main_a188dda414440213c8768efbfc4fa4d8,body.awakenology-toc-page #wb_main_a188dda4144403b540310ab683472666{padding-top:10px!important}body.awakenology-toc-page h2.wb-stl-heading2{font-size:29px!important;margin-bottom:10px!important}body.awakenology-toc-page .wb-stl-heading2 + p{margin-bottom:20px!important}}
html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color:#333333"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color: #333333"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color:#000000"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color: #000000"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color:#272626"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color: #272626"],html[data-aw-theme="dark"] [style*="color:#1f3864"],html[data-aw-theme="dark"] [style*="color: #1f3864"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color:#1f3864"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color: #1f3864"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color:rgb(39, 38, 38)"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="color: rgb(39, 38, 38)"]{color:#e8e8e8!important}
html[data-aw-theme="dark"] body.awakenology-chinese-page #a19c93e79d1100245860cc6f0d48686a,html[data-aw-theme="dark"] body.awakenology-chinese-page #a19c93e79d1100245860cc6f0d48686a > .wb_content{background:#2b2514!important;background-color:#2b2514!important}
html[data-aw-theme="dark"] body.awakenology-chinese-page .wb_content{background-color:#121212!important;color:#e8e8e8!important}
html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color:#41464b"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color: #41464b"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color:#333333"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color: #333333"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color:#000000"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color: #000000"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color:#272626"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color: #272626"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color:rgb(39, 38, 38)"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="color: rgb(39, 38, 38)"]{color:#e8e8e8!important}
html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="background:#ffffff"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="background: #ffffff"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="background-color:#ffffff"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="background-color: #ffffff"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="background:rgb(255, 255, 255)"],html[data-aw-theme="dark"] body.awakenology-chinese-page [style*="background: rgb(255, 255, 255)"]{background:#121212!important;background-color:#121212!important}
html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="background:#ffffff"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="background: #ffffff"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="background-color:#ffffff"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="background-color: #ffffff"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="background:rgb(255, 255, 255)"],html[data-aw-theme="dark"] body.awakenology-legacy-dark-page [style*="background: rgb(255, 255, 255)"]{background:#121212!important;background-color:#121212!important}
html[data-aw-theme="dark"] body.site-lang-en #a19e7e93bc1d0a3dd101e0022a644444 > .wb_content{background:#2b2514!important;background-color:#2b2514!important}
html[data-aw-theme="dark"] p,html[data-aw-theme="dark"] li,html[data-aw-theme="dark"] h1,html[data-aw-theme="dark"] h2,html[data-aw-theme="dark"] h3,html[data-aw-theme="dark"] h4,html[data-aw-theme="dark"] h5,html[data-aw-theme="dark"] h6,html[data-aw-theme="dark"] .wb-stl-normal,html[data-aw-theme="dark"] .wb-stl-footer{color:#e8e8e8!important}
html[data-aw-theme="dark"] body.site-lang-en #a188dda404b603086d7b3027a1d90739 span[style*="background-color:#ffffff"],html[data-aw-theme="dark"] body.site-lang-en #a188dda404b603086d7b3027a1d90739 span[style*="background-color: #ffffff"]{background-color:transparent!important;color:#e8e8e8!important}
html[data-aw-theme="dark"] a{color:#9ecbff!important}
#awakenology-theme-toggle{position:fixed;top:10px;right:10px;z-index:2147483647;border:1px solid #888;border-radius:14px;width:30px;height:30px;padding:4px;font:18px/20px "Segoe UI Symbol",Arial,sans-serif;cursor:pointer;background:#fff;color:#222;box-shadow:0 1px 4px #0004}
html[data-aw-theme="dark"] #awakenology-theme-toggle{background:#222;color:#eee;border-color:#777}

#awakenology-return-top{position:fixed;right:10px;bottom:10px;z-index:2147483647;border:1px solid #888;border-radius:14px;width:30px;height:30px;padding:4px;font:18px/20px Arial,sans-serif;cursor:pointer;background:#fff;color:#222;box-shadow:0 1px 4px #0004;display:none}
html[data-aw-theme="dark"] #awakenology-return-top{background:#222;color:#eee;border-color:#777}
footer .footer-inner{max-width:760px!important;margin:0 auto!important;display:flex!important;flex-direction:column!important;justify-content:center!important;align-items:center!important;gap:10px!important;color:inherit!important;font-size:13px!important}footer .footer-links{display:flex!important;align-items:center!important;justify-content:center!important;gap:12px!important;flex-wrap:wrap!important;margin:0!important}footer .contact-icon,footer .disclaimer-icon{display:inline-flex!important;width:24px!important;height:24px!important;align-items:center!important;justify-content:center!important;font-size:20px!important;line-height:1!important;text-decoration:none!important}footer .contact-icon:hover,footer .disclaimer-icon:hover{text-decoration:none!important}
</style>
<style id="awakenology-cn-style">
#awakenology-cn-toggle{position:fixed;top:10px;right:54px;z-index:2147483647;border:1px solid #888;border-radius:14px;min-width:30px;height:30px;padding:4px 7px;font:14px/20px Arial,sans-serif;cursor:pointer;background:#fff;color:#222;box-shadow:0 1px 4px #0004}
html[data-aw-theme="dark"] #awakenology-cn-toggle{background:#222;color:#eee;border-color:#777}
</style>`;

    const script = `<script>
(function(){var KEY="awakenology-theme";var saved=localStorage.getItem(KEY);var dark=saved!=="light";document.documentElement.setAttribute("data-aw-theme",dark?"dark":"light");document.addEventListener("DOMContentLoaded",function(){if(!document.getElementById("awakenology-theme-toggle")&&!document.getElementById("theme-toggle")&&!document.querySelector(".theme-toggle")){var button=document.createElement("button");button.id="awakenology-theme-toggle";button.type="button";button.setAttribute("aria-label","Switch background theme");button.textContent=dark?"☀︎":"☾︎";button.addEventListener("click",function(){dark=document.documentElement.getAttribute("data-aw-theme")!=="dark";document.documentElement.setAttribute("data-aw-theme",dark?"dark":"light");localStorage.setItem(KEY,dark?"dark":"light");button.textContent=dark?"☀︎":"☾︎"});document.body.appendChild(button)}if(document.getElementById("awakenology-return-top"))return;var topButton=document.createElement("button");topButton.id="awakenology-return-top";topButton.type="button";topButton.setAttribute("aria-label","Return to top");topButton.title="Return to top";topButton.textContent="↑";function updateTop(){topButton.style.display=window.scrollY>300?"block":"none"}topButton.addEventListener("click",function(){window.scrollTo({top:0,behavior:"smooth"})});window.addEventListener("scroll",updateTop,{passive:true});updateTop();document.body.appendChild(topButton)})}());
</script>`;

    const chineseScript = `<script type="module">\n(function(){function looksChinesePage(){var text=document.body?(document.body.innerText||""):"";var han=(text.match(/[\\u3400-\\u9fff]/g)||[]).length;var kana=(text.match(/[\\u3040-\\u30ff]/g)||[]).length;var signals=(text.match(/[的了是我你他她這这個个與与為为會会來来說说時时間间麼么沒没還还從从們们]/g)||[]).length;return han>=30&&kana===0&&signals>=2}\nfunction init(){if(!(document.body.classList.contains("awakenology-chinese-page")||looksChinesePage())||document.getElementById("awakenology-cn-toggle"))return;import("https://cdn.jsdelivr.net/npm/opencc-js@1.4.1/dist/esm/full.js").then(function(module){var OpenCC=module.default||module;var saved=localStorage.getItem("awakenology-cn-variant");var originalBody=document.body.innerHTML;var originalTitle=document.title;var activeVariant="tw";var target=saved==="cn"?"cn":"tw";var toSimplified=OpenCC.Converter({from:"tw",to:"cn"});var toTraditional=OpenCC.Converter({from:"cn",to:"tw"});\nfunction convertTextNodes(converter){var walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);var nodes=[];var node;while(node=walker.nextNode())nodes.push(node);nodes.forEach(function(n){if(n.parentElement&&n.parentElement.closest("#awakenology-cn-toggle"))return;if(n.nodeValue&&n.nodeValue.trim())n.nodeValue=converter(n.nodeValue)});document.title=converter(document.title)}\nfunction applyVariant(variant){var themeButton=document.getElementById("awakenology-theme-toggle");var topButton=document.getElementById("awakenology-return-top");document.body.innerHTML=originalBody;document.title=originalTitle;activeVariant=variant;if(variant==="cn")convertTextNodes(toSimplified);else convertTextNodes(toTraditional);document.documentElement.setAttribute("lang",variant==="cn"?"zh-CN":"zh-Hant");document.body.setAttribute("lang",variant==="cn"?"zh-CN":"zh-Hant");localStorage.setItem("awakenology-cn-variant",variant);button.textContent=variant==="tw"?"简":"繁";button.setAttribute("aria-label",variant==="tw"?"Convert to Simplified Chinese":"Convert to Traditional Chinese");if(themeButton)document.body.appendChild(themeButton);if(topButton)document.body.appendChild(topButton);document.body.appendChild(button)}\nvar button=document.createElement("button");button.id="awakenology-cn-toggle";button.className="ignore-opencc ignore-translate";button.type="button";button.textContent=target==="tw"?"简":"繁";button.setAttribute("aria-label",target==="tw"?"Convert to Simplified Chinese":"Convert to Traditional Chinese");button.title="繁 / 简";button.addEventListener("click",function(){applyVariant(activeVariant==="tw"?"cn":"tw")});document.body.appendChild(button);if(target==="cn")applyVariant("cn")}).catch(function(error){console.error("Awakenology Chinese toggle failed:",error)})}\nif(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init()}());\n</script>`;

    return new HTMLRewriter()
      .on("link",{element(el){var rel=(el.getAttribute("rel")||"").toLowerCase().split(/\\s+/);if(rel.includes("icon")||rel.includes("apple-touch-icon"))el.remove()}})
      .on("body",{element(el){var current=el.getAttribute("class")||"";if(isLanguageTocPage)current+=" awakenology-toc-page";if(decodedPathname==="/English/")current+=" awakenology-lang-en";if(decodedPathname==="/Japanese/")current+=" awakenology-lang-ja";if(decodedPathname==="/Chinese/")current+=" awakenology-lang-zh";if(isLegacyDarkPage)current+=" awakenology-legacy-dark-page";if(isChinesePage)current+=" awakenology-chinese-page";el.setAttribute("class",current)}})
      .on("head",{element(el){el.append(theme+script+chineseScript+"<link rel=\"icon\" type=\"image/png\" href=\"/gallery/favicons/favicon.png\">",{html:true})}})
      .on("footer",{element(el){el.setInnerContent("<div class=\"footer-inner\" style=\"max-width:760px;margin:0 auto;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:10px;color:inherit;font-size:13px\"><span class=\"footer-links\" style=\"display:flex;align-items:center;justify-content:center;gap:12px;flex-wrap:wrap;margin:0\"><a class=\"contact-icon\" href=\"mailto:contact@awakenology.org\" aria-label=\"Email Awakenology\" title=\"Contact\"><span aria-hidden=\"true\">✉</span></a><a class=\"reddit-icon reddit-one\" href=\"https://www.reddit.com/r/EscapeReincarnation/\" aria-label=\"Reddit: Escape Reincarnation\"><img src=\"/assets/reddit-one.svg\" alt=\"\"></a><a class=\"reddit-icon reddit-two\" href=\"https://www.reddit.com/r/EscapePrisonPlanet/\" aria-label=\"Reddit: Escape Prison Planet\"><img src=\"/assets/reddit-two.svg\" alt=\"\"></a><a class=\"reddit-icon reddit-three\" href=\"https://www.reddit.com/user/Lower-Lingonberry-40/\" aria-label=\"Reddit: Lower-Lingonberry-40\"><img src=\"/assets/reddit-three.svg\" alt=\"\"></a><a class=\"disclaimer-icon\" href=\"/Disclaimer/\" aria-label=\"Disclaimer\" title=\"Disclaimer\"><span aria-hidden=\"true\">ⓘ</span></a></span><span>© 2017 Awakenology</span></div>" ,{html:true})}})
      .transform(response);
  }
};
/* Cloudflare rebuild trigger 2026-10-03 */
